import { findAllProducts, updateProduct } from '@/products/db';
import OpenAI from 'openai';
import pLimit from 'p-limit';

const client = new OpenAI();

const INTERESTS = [
  "3D Printing",
  "Accessibility",
  "Accounting & Finance",
  "Acting",
  "Action and Adventure Movies",
  "Action Video Games",
  "activism",
  "Adult Education",
  "Adventure Travel",
  "Adventure Video Games",
  "Adventure",
  "Advocacy",
  "Affiliate marketing",
  "Agriculture",
  "AI",
  "Alternative Medicine",
  "Alternative Music",
  "Alternative Rock",
  "Amateur Radio",
  "American Football",
  "Analytics",
  "Angel Investment",
  "animals",
  "Anime",
  "Anthropology",
  "Antiquing and Antiques",
  "Apple",
  "Archery",
  "Architecture",
  "Art",
  "Artificial Intelligence",
  "Arts and Crafts",
  "arts",
  "Astrology",
  "Astronomy",
  "Audio Production",
  "Augmented Reality",
  "Australian Rules Football",
  "Author",
  "Auto Buying and Selling",
  "Auto Racing",
  "Auto Shows",
  "Auto Technology",
  "Automation",
  "Aviation",
  "Backpacking",
  "Badminton",
  "baking",
  "Baseball",
  "Basketball",
  "BBQ",
  "Beach Volleyball",
  "Beadwork",
  "Beauty",
  "Beekeeping",
  "Bible Study",
  "Biking",
  "Billiards",
  "Biographies",
  "Bioinformatics",
  "Biology",
  "Birdwatching",
  "Bitcoin",
  "blockchain",
  "Blogging",
  "Blues",
  "Board Games",
  "Boating",
  "Body Art",
  "Bodybuilding",
  "Books",
  "Bowling",
  "Boxing",
  "branding",
  "Budget Cars",
  "Business and Finance",
  "Business Growth",
  "Business",
  "Calligraphy",
  "Camping",
  "Candle and Soap Making",
  "Cannabis",
  "Canoeing and Kayaking",
  "Car Culture",
  "Car Racing",
  "Card Games",
  "Career Advice",
  "cars",
  "Cartoons",
  "Casual Games",
  "Cats",
  "Cheerleading",
  "Chemistry",
  "Chess",
  "Children's Clothing",
  "Children's Literature",
  "Children's Music",
  "Christianity",
  "Church",
  "Cinema",
  "Civil Rights",
  "Classic Cars",
  "Classic Hits",
  "Classic Rock",
  "Classical Music",
  "cleaning",
  "Climate change",
  "Climbing",
  "Clinical Science",
  "Cloud Computing",
  "Coaching",
  "Coding",
  "Coffee",
  "Collecting",
  "College Baseball",
  "College Basketball",
  "College Football",
  "College Radio",
  "College Sports",
  "Comedy Movies",
  "comedy",
  "Comic Books",
  "Comics and Graphic Novels",
  "communication",
  "Community",
  "Compliance",
  "Composing",
  "Computer Science",
  "Computer Vision",
  "Computers",
  "Concept Cars",
  "Concerts",
  "consciousness",
  "Construction",
  "CONSULTING",
  "Consumer Electronics",
  "Content Creation",
  "Content Marketing",
  "Content Production",
  "content writing",
  "Cookbooks",
  "Cooking",
  "Copywriting",
  "Cosplay",
  "Counseling",
  "Country Music",
  "Crafting",
  "Creative Writing",
  "Creativity",
  "Cricket",
  "Crime and Mystery Movies",
  "Critical Thinking",
  "crochet",
  "CrossFit",
  "Cryptocurrency",
  "culture",
  "Cyber Security",
  "Cycling",
  "Daily Essentials",
  "Dance and Electronic Music",
  "Dancing",
  "Darts",
  "Data Analysis",
  "Data Science",
  "Deep Learning",
  "Design",
  "Designer Clothing",
  "Desserts and Baking",
  "Digital Art",
  "Digital Marketing",
  "Digital transformation",
  "Dinosaurs",
  "Disabled Sports",
  "Disney",
  "Diving",
  "DIY Projects",
  "DJing",
  "Documentary Movies",
  "Dogs",
  "Drama Movies",
  "drawing",
  "Driverless Cars",
  "Driving",
  "drones",
  "Drums",
  "Dungeons and Dragons",
  "Ecology",
  "Ecommerce",
  "Economics",
  "Editing",
  "Education",
  "Educational Video Games",
  "Electrical Engineering",
  "Electronics",
  "Elementor",
  "Email marketing",
  "Embroidery",
  "Engineering",
  "English",
  "Entertainment",
  "entrepreneurship",
  "Environmental Science and Sustainability",
  "Environmentalism",
  "Equine Sports",
  "eSports",
  "Ethereum",
  "ethical hacking",
  "Events",
  "exercise",
  "Extreme Sports",
  "Faith",
  "Family",
  "Fantasy Movies",
  "Fantasy Sports",
  "Farming",
  "Fashion",
  "Fiction",
  "Field Hockey",
  "Figure Skating",
  "Film",
  "Filmmaking",
  "Finance",
  "Financial Services",
  "Fine Art Photography",
  "Fintech",
  "Fish and Aquariums",
  "Fishing",
  "Fitness",
  "Flutter",
  "Food",
  "Football",
  "Formula 1",
  "Freelance Writing",
  "Friends",
  "Frugal Living",
  "Furniture",
  "Fussball",
  "Gadgets",
  "Game Development",
  "Games and Puzzles",
  "Gaming",
  "Gardening",
  "Genealogy",
  "Generative AI",
  "Genetics",
  "Geocaching",
  "Geography",
  "Geology",
  "Geopolitics",
  "God",
  "Golf",
  "Gospel Music",
  "Governance and Society",
  "graphic design",
  "Gravatar",
  "Green Vehicles",
  "growth",
  "guitar",
  "GYM",
  "Gymnastics",
  "Hacking",
  "Hard Rock",
  "Hardware",
  "Health and Wellness",
  "Health Supplements",
  "Health",
  "Healthy Cooking and Eating",
  "Healthy Living",
  "Heavy Metal",
  "Herbs and Supplements",
  "High Fashion",
  "Higher Education",
  "Hiking",
  "Hip Hop Music",
  "History",
  "Holistic Health",
  "home decor",
  "Home Entertaining",
  "Home Improvement",
  "homesteading",
  "Horror Movies",
  "Horse Racing",
  "Horseback Riding",
  "Horses and Equine",
  "Hospitality",
  "Human Resources",
  "Human Rights",
  "Humor and Satire",
  "Hunting and Shooting",
  "Hunting",
  "Ice Hockey",
  "Illustration",
  "Improv Comedy",
  "Indie and Arthouse Movies",
  "Information Technology",
  "Inline Skating",
  "Innovation",
  "Inspirational/New Age Music",
  "Insurance",
  "Interior Decorating",
  "Interior Design",
  "International Relations",
  "Internet of Things",
  "Internet",
  "Investing",
  "Investment",
  "islam",
  "Japan",
  "Japanese",
  "Jazz",
  "Jesus",
  "Jewelry Making",
  "Journaling",
  "Journalism",
  "Juggling",
  "Karate",
  "Kayaking",
  "Kickboxing",
  "Kids",
  "Knitting",
  "Kpop",
  "Lacrosse",
  "Landscaping",
  "Language Learning",
  "Languages",
  "Large Animals",
  "Law",
  "Leadership",
  "learning",
  "lecture",
  "Lego",
  "LGBTQ",
  "Life Sciences",
  "Lifestyle",
  "Linguistics",
  "linux",
  "Literature",
  "live music",
  "Logistics",
  "Logo design",
  "love",
  "Luxury Cars",
  "Machine Learning",
  "Magic and Illusion",
  "Makeup",
  "Manga",
  "Manufacturing",
  "Marketing and Advertising",
  "marketing",
  "Martial Arts",
  "Marvel",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine and Healthcare",
  "Meditation",
  "Men's Fashion",
  "Men's Health",
  "mental health",
  "Mentoring",
  "Mergers and Acquisitions",
  "Metal Music",
  "Mindfulness",
  "mindset",
  "Minecraft",
  "MMOs",
  "mobile app development",
  "Mobile Games",
  "Model Toys",
  "Modern Art",
  "money",
  "Motherhood",
  "Motorcycle Sports",
  "Motorcycles",
  "Motorcycling",
  "Mountain Biking",
  "Mountain Climbing",
  "Mountains",
  "Movies",
  "Music and Art",
  "Music and Audio",
  "Music Production",
  "Music",
  "Musical Instruments",
  "Musicals",
  "Mythology",
  "Nature photography",
  "Nature",
  "NBA",
  "Needlework",
  "networking",
  "neurodiversity",
  "Neuroscience",
  "News",
  "NFL",
  "Nintendo",
  "Non-Alcoholic Beverages",
  "Nutrition",
  "Oldies/Adult Standards",
  "Olympic Sports",
  "Online business",
  "Online Education",
  "open source",
  "Opera",
  "Origami",
  "Outdoor Decorating",
  "Outdoors",
  "Paintball",
  "Painting",
  "Paranormal Phenomena",
  "Parenting",
  "PC Games",
  "peace",
  "Performance Cars",
  "Personal Care",
  "Personal development",
  "Personal Finance",
  "Personal Investing",
  "Pet Adoptions",
  "Pets",
  "Philosophy",
  "Photography",
  "Photoshop",
  "Physical Therapy",
  "Physics",
  "Piano",
  "Pickleball",
  "Pilates",
  "Pizza",
  "Plants",
  "plumbing",
  "podcasting",
  "Podcasts",
  "Poetry",
  "Pokemon",
  "Poker and Professional Gambling",
  "Politics",
  "Pop Culture",
  "Pottery",
  "Prayer",
  "Privacy",
  "Problem Solving",
  "Product Design",
  "Product Management",
  "Productivity",
  "Programming Languages",
  "Programming",
  "Project Management",
  "Psychology",
  "Public Radio",
  "public relations",
  "Public Speaking",
  "Publishing",
  "Puzzle Video Games",
  "Quantum Mechanics",
  "Quantum physics",
  "Quilting",
  "R&B/Soul/Funk",
  "Radio Control",
  "Radio",
  "RC Vehicles",
  "Reading books",
  "Reading",
  "Real Estate",
  "Recipes",
  "Reggae",
  "Reiki",
  "relationships",
  "Religion",
  "Religious Music",
  "Remodeling & Construction",
  "Remote Working",
  "Reptiles",
  "Research Methods",
  "Research Paper Writing",
  "Research",
  "Retail",
  "Retirement Planning",
  "Retro",
  "Risk Management",
  "roblox",
  "Robotics",
  "Rock Climbing",
  "Rock Music",
  "Rodeo",
  "Role-Playing Video Games",
  "Roleplaying Games",
  "Rollerblading",
  "Romance Movies",
  "Rowing",
  "Rugby League",
  "Rugby Union",
  "Rugby",
  "Running",
  "Rust",
  "SaaS",
  "Sailing",
  "Sales",
  "Sci-fi and Fantasy",
  "Science Fiction Movies",
  "Science Fiction",
  "Science",
  "Scooters",
  "Scrapbooking",
  "Screenwriting",
  "Scuba Diving",
  "Sculpture",
  "Search Engine Optimization",
  "security",
  "self improvement",
  "SEO",
  "Series",
  "Server",
  "Sewing",
  "Shopping",
  "Showtunes",
  "Simulation Video Games",
  "Singing",
  "Skateboarding",
  "Ski",
  "Skiing",
  "Skin Care",
  "Skydiving",
  "sleep",
  "sleeping",
  "Small Business",
  "Smart Home",
  "Snowboarding",
  "Soap Making",
  "Soccer",
  "Social Media Marketing",
  "social media",
  "Social Networking",
  "Social Sciences",
  "Sociology",
  "Soft Rock",
  "Softball",
  "Software development",
  "Software Engineering",
  "Songwriting",
  "sound design",
  "Space and Astronomy",
  "Spirituality",
  "Sport",
  "Sports Equipment",
  "Sports Radio",
  "Sports Video Games",
  "Sports",
  "Squash",
  "Stamp Collecting",
  "Stamps and Coins",
  "Stand-Up Comedy",
  "star wars",
  "Startups",
  "Statistics",
  "Stocks",
  "Storytelling",
  "Strategy Video Games",
  "Strategy",
  "Streaming",
  "Street Style",
  "Style & Fashion",
  "Summer Olympic Sports",
  "Surfing and Bodyboarding",
  "Surfing",
  "Sustainability",
  "Swimming",
  "Table Tennis",
  "Tai Chi",
  "Talk Radio",
  "Tarot",
  "Tattoos",
  "Tea",
  "Teaching",
  "Tech",
  "Technology",
  "Television",
  "Tennis",
  "Theater",
  "Theology",
  "Therapy",
  "Thrifting",
  "Top 40 Music",
  "Tourism",
  "Track and Field",
  "Trade",
  "Trading",
  "translation",
  "Travel Books",
  "Travel",
  "Trekking",
  "True Crime",
  "TTRPGs",
  "TV Shows",
  "UI Design",
  "Upcycling",
  "Urban Contemporary Music",
  "UX Design",
  "Variety (Music and Audio)",
  "Vegan Diets",
  "Vegetarian Diets",
  "Venture Capital",
  "Video Editing",
  "Video Games",
  "Video Production",
  "Video",
  "Videography",
  "Virtual Reality",
  "Vlogging",
  "Vocational Training",
  "Volleyball",
  "Volunteering",
  "Walking",
  "Watching Documentaries",
  "Water Polo",
  "Waterskiing and Wakeboarding",
  "Weather",
  "Web design",
  "Web Development",
  "Web Hosting",
  "webdesign",
  "Wedding",
  "Weight Loss",
  "Weightlifting",
  "Wellbeing",
  "Wellness",
  "Whittling",
  "wildlife",
  "Wine Tasting",
  "Winter Olympic Sports",
  "Women's Fashion",
  "Women's Health",
  "WooCommerce",
  "Woodworking",
  "WordPress",
  "Workshops and Classes",
  "World Cuisines",
  "World Movies",
  "World/International Music",
  "Wrestling",
  "Writing",
  "Yoga",
  "Young Adult Literature",
  "Youtube",
];

const GPT4_INPUT_PRICE_PER_1M = 0.2;
const GPT4_OUTPUT_PRICE_PER_1M = 0.8;

const { products } = (await findAllProducts(1, Number.MAX_SAFE_INTEGER, true));

let i = 0;
let totalInputTokens = 0;
let totalOutputTokens = 0;

const limit = pLimit(3);

await Promise.all(products.map(product => limit(async () => {
  console.log(`(${++i}/${products.length}) - ${product.productName} - Processing product`);

  if (product.interests?.length === 7) {
    console.log(`(${i}/${products.length}) - ${product.productName} - Skipping product with interests already calculated`);
    return;
  }

  const instructions = `You are an expert ecommerce analyst. Your task is to analyze product details and generate a list of relevant interests that would appeal to potential customers. Consider the following aspects:
    1. Product name and description
    2. Target audience demographics
    3. Lifestyle and values associated with the product
    4. Related hobbies and activities
    5. Complementary interests
    6. Seasonal or occasion-based interests
    7. Price point implications
    8. Brand positioning and values

    Interests should:
     - be specific but not too niche
     - be specific to an interest a person might have

    Restrict the interests ONLY to the following list:
    ${INTERESTS.join("\n-")}

    Return a JSON array of interests, maximum 7, where each interest is a string.`;

  const input = JSON.stringify({
    productName: product.productName,
    description: product.description,
    storeName: product.shopName
  });

  const response = await client.responses.create({
    model: 'gpt-4.1-mini',
    instructions,
    input
  });

  // Count input tokens
  const inputTokens = response.usage?.input_tokens ?? 0;
  totalInputTokens += inputTokens;

  // Count output tokens
  const outputTokens = response.usage?.output_tokens ?? 0;
  totalOutputTokens += outputTokens;

  console.log(`(${i}/${products.length}) Token usage for this product:`);
  console.log(`- Input tokens: ${inputTokens}`);
  console.log(`- Output tokens: ${outputTokens}`);
  console.log(`- Estimated cost: $${((inputTokens * GPT4_INPUT_PRICE_PER_1M / 1_000_000) + (outputTokens * GPT4_OUTPUT_PRICE_PER_1M / 1_000_000)).toFixed(4)}`);

  try {
    const interests = JSON.parse(response.output_text.replace(/^```json\n/, '').replace(/\n```$/, ''));
    console.log(`(${i}/${products.length}) - ${product.productName} - Calculated interests`, interests);

    await updateProduct({
      ...product,
      interests: interests.map((interest: string) => interest.toLowerCase()),
    });
  } catch (error) {
    console.error(`(${i}/${products.length}) - ${product.productName} - Error calculating interests`, error);
    console.log('--');
    console.log(response.output_text);
    console.log('--');
  }
})));

// Print total usage and cost
console.log('\nTotal token usage:');
console.log(`- Total input tokens: ${totalInputTokens}`);
console.log(`- Total output tokens: ${totalOutputTokens}`);
console.log(`- Total estimated cost: $${((totalInputTokens * GPT4_INPUT_PRICE_PER_1M / 1_000_000) + (totalOutputTokens * GPT4_OUTPUT_PRICE_PER_1M / 1_000_000)).toFixed(4)}`);
